### ISSUE TITLE
[add a voting system] STAR voting

### ISSUE THREAD

**Issue by wolftune** [ncase/ballot#15]
STAR voting is Score Then Automatic Runoff, a slight tweak of score. It's still pretty simply to explain and understand, and it's not just theoretical. http://www.equal.vote/ is actually in process of getting it on the 2018 ballot to be potentially implemented in two counties in Oregon. So this isn't bonus for the math nerds, this is real deal stuff that people need to understand!

It should be very easy to add, it's not complex mathematically.

**Comment by endolith** [comment]
This can be closed because of [#18 ](https://github.com/ncase/ballot/pull/18#issuecomment-398539684)

**Comment by wolftune** [comment]
But even though this was done by someone, is there not some possibility of adding a *link* or *something* so that people who visit the original can learn that the new variants exist??
