### ISSUE TITLE
Prepare public translations

### ISSUE THREAD

**Issue by aunwin** [ncase/ballot#22]
If you would be so kind to prepare public translations to this work of yours as you did with Attractor Landscapes, helping with translation without the fear of altering something you would not want to be altered.
The idea that I would like to help translate this work of yours came up since there have been some rather disturbing ballots in Germany just recently. Maybe I thought, this explorable explanation should also be available for non english speakers.

**Comment by yaap7** [comment]
I have the exact same request, to translate it in french. I tried to contact @ncase without luck, so I was starting a french translation on my side before discovering this post.
Do you need something specific we can help to prepare the translation?

I was going to fork the repo to translate a fresh copy. Is it a good way to translate?

**Comment by pourdamghani** [comment]
Hi @ncase,
I also want to translate this article, if possible, into Persian. We are well aware that this article is in the public domain, but permission from you would be a nice boost for us.
We already [finished](https://mehdi-mostafavi.github.io/covid-19) the translation of COVID-19. Thanks a lot for the playable explanation about COVID. It was very informative.
And, I have sent an email regarding our research on novel voting systems months ago and asked for your insight, but you never responded back :(

**Comment by yaap7** [comment]
About my request to translate it in french, I finally found someone already did it here: https://github.com/xDEADC0DE/ballot-fr
In addition, a live instance is available here: https://pour-un-meilleur-scrutin.fr/

So, there is no more issue about french translation. Sorry for the confusion.

**Comment by pourdamghani** [comment]
[Persian Translation](https://pourdamghani.github.io/ballot/) has also finished. That would be awsome to add a link to these version in the main article @ncase :)

**Comment by ncase** [comment]
![image](https://user-images.githubusercontent.com/825858/89222375-f16b9800-d5a2-11ea-971a-b42a1260860f.png)

French & Persian translations are linked to from the main page, thanks for this suggestion to have links to public translations! Also, sorry for getting to this so late – my email inbox is full of hundreds of unread stuff, many high-priority, so this got lost. Thank you all again for taking the time & effort to contribute to this! 🎉
