### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ignyx** [ncase/ballot#24]
Sadly, "Canada's Cutie-In-Chief"'s picture is missing :(

The [Canada's Cutie-In-Chief link](http://cdn.pinknews.co.uk/images/2016/02/justin_trudeau.jpg) in [index.html](../blob/gh-pages/index.html) line 159 is no longer served. I would open a pull request with an alternative but I feel like, given the name, the picture was special and I do not believe it is my place to do so.

**Comment by devxan** [comment]
A PR could be made replacing broken links like the one you mentioned with archives via the Wayback Machine: https://web.archive.org/web/20170629225717/http://cdn.pinknews.co.uk/images/2016/02/justin_trudeau.jpg

I clicked a few other links that led to errors, and the original pages were on the Internet Archive.

**Comment by ignyx** [comment]
Good idea ! I'll give it a go
