### ISSUE TITLE
Breaking "Public Domain" line in the footer overlaps text

### ISSUE THREAD

**Issue by blinry** [ncase/ballot#8]
![screenshot-2017-02-03_11 49 02](https://cloud.githubusercontent.com/assets/81277/22607722/61f7e1e8-ea59-11e6-9ddc-d62239449f95.png)

This happens in Chromium 56.0.2924.76 on Arch Linux. My screen has a rather high resolution (2560x1440), but it occurs for each browser window size.

**Comment by ncase** [comment]
Fixed! Just reduced the font-size by 2px.

**Comment by blinry** [comment]
Can confirm fix, thanks! :)
